### ISSUE TITLE
Update recipe endpoint fails if batchSize is given as string

### ISSUE THREAD

**Issue by tarvainen** [sahtivahti/apigw#11]
```
Connection id "0HLSH6858ILC5", Request id "0HLSH6858ILC5:0000000B": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at apigw.Controllers.RecipeController.UpdateRecipe(Recipe recipe, Int32 id) in /src/Controllers/RecipeController.cs:line 46
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
```

**Comment by tarvainen** [comment]
Fixed in #12
